/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ContextMenu {
    /**
    * Closes the menu
    */
    'close': () => Promise<any>;
    /**
    * Overlapping of child <> parent menus in pixel (default `8`)
    */
    'horizontalOverlap': number;
    /**
    * Opens the menu
    */
    'open': (pos: any) => Promise<any>;
    /**
    * Sets the css attribute z-index to a custom value. Default is `100` whereas every child increments the value of its parent by one.
    */
    'zIndex': number;
  }
  interface ContextMenuAttributes extends StencilHTMLAttributes {
    /**
    * Overlapping of child <> parent menus in pixel (default `8`)
    */
    'horizontalOverlap'?: number;
    /**
    * Fires when the menu is `close`d
    */
    'onHide'?: (event: CustomEvent) => void;
    /**
    * Fires on `mouse down` of any row with the attribute `data-group`
    */
    'onSelect'?: (event: CustomEvent) => void;
    /**
    * Fires when the menu is `open`ed
    */
    'onShow'?: (event: CustomEvent) => void;
    /**
    * Fires on `mouse down` of any row with the attribute `data-toggle`
    */
    'onToggle'?: (event: CustomEvent) => void;
    /**
    * Sets the css attribute z-index to a custom value. Default is `100` whereas every child increments the value of its parent by one.
    */
    'zIndex'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ContextMenu': Components.ContextMenu;
  }

  interface StencilIntrinsicElements {
    'context-menu': Components.ContextMenuAttributes;
  }


  interface HTMLContextMenuElement extends Components.ContextMenu, HTMLStencilElement {}
  var HTMLContextMenuElement: {
    prototype: HTMLContextMenuElement;
    new (): HTMLContextMenuElement;
  };

  interface HTMLElementTagNameMap {
    'context-menu': HTMLContextMenuElement
  }

  interface ElementTagNameMap {
    'context-menu': HTMLContextMenuElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
